#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import subprocess

# `scons p=linux` to compile for linux
# `scons p=windows` to compile for windows

# on linux you can optionally use `use_llvm=yes` to use clang instead of gcc

project_name = "vulkan_tutorial"
output_folder = "bin/"

# TODO Platform-independent Vulkan SDK path
vulkan_sdk_dir = "/home/bigo/Downloads/1.3.216.0"

#------------------------------------------------------------------------------
# my glsllang converter build
shader_bld = Builder(action = "glslangValidator -V $SOURCE -o $TARGET")
import os
env = Environment(ENV = {'PATH' : os.environ['PATH']})
#env = Environment()

if ARGUMENTS.get('use_llvm', 'no') == 'yes':
	env['CXX'] = 'clang++'

target = ARGUMENTS.get('target', 'release')
platform = ARGUMENTS.get('p', 'linux')

#------------------------------------------------------------------------------
if ARGUMENTS.get('compile_shaders', 'no') == 'yes':

	def compile_shaders():
		# TODO Platform-independent shader compilation
		compiler_path = os.path.join(vulkan_sdk_dir, "x86_64/glslangValidator")
		shaders = [
			"shaders/default.frag",
			"shaders/default.vert"
		]
		for shader in shaders:
			print("Compiling shader ", shader)
			target_path = os.path.join(output_folder, os.path.basename(shader) + '.spv')
			subprocess.call([compiler_path, '-V', shader, '-o', target_path])

	compile_shaders()

#------------------------------------------------------------------------------
#env['TARGET_ARCH'] = 'x86_64'

env.Append(LIBS = [
	"vulkan",
	"glfw"
])
env.Append(CPPPATH = [
	"thirdparty/glfw/include",
    "./include",
	"/home/bigo/Downloads/1.3.216.0/x86_64/include"
	"."
])
env.Append(CPPDEFINES = [
])
env.Append(VULKAN_SDK="/home/bigo/Downloads/1.3.216.0/x86_64")
env.Append(LD_LIBRARY_PATH="$VULKAN_SDK/lib")
env.Append(VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d")

if platform == 'linux':

	env.Append(CCFLAGS = ['-g','-O3', '-std=c++14'])
	env.Append(LINKFLAGS = ['-Wl,-R,\'$$ORIGIN\''])
	# TODO Linux setup
#------------------------------------------------------------------------------
sources = []

def add_sources(sources, dir):
	for f in os.listdir(dir):
		if f.endswith('.cpp') or f.endswith('.c'):
			sources.append(dir + '/' + f)

add_sources(sources, 'src')
#------------------------------------------------------------------------------

env.Append(BUILDERS ={"ShaderComp":shader_bld})
env.ShaderComp("src/vert.spv","src/shader.vert")
env.ShaderComp("src/frag.spv","src/shader.frag")
env.Program(target=(output_folder + project_name), source=sources)
# Default(program)